name: Production Deploy (Vercel)

on:
  push:
    branches: [main]
    paths:
      - "frontend/login-microfrontend/**"

permissions:
  contents: read
  deployments: write

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/login-microfrontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Opcional) podemos omitir build local porque el CI ya valida
      # - name: Install deps
      #   run: npm ci
      # - name: Build local
      #   run: npm run build

      - name: Deploy to Vercel (Production, remote build)
        uses: amondnet/vercel-action@v41.1.4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: ./frontend/login-microfrontend
