name: Production Deploy (Vercel)

on:
  push:
    branches: [main]
    paths:
      - "frontend/login-microfrontend/**"

permissions:
  contents: read
  deployments: write

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/login-microfrontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/login-microfrontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (prebuilt para Vercel)
        run: npm run build

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v41.1.4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod --prebuilt"
          working-directory: ./frontend/login-microfrontend
